ciber:
  - ransomware
  - phishing
  - breach
  - ciberataque
  - vulnerabilidad
  - malware
  - DDoS
  - data leak
fraude:
  - fraude
  - estafa
  - lavado
  - ponzi
  - esquema piramidal
  - falsificación
  - suplantación
  - timo
operacional:
  - interrupción
  - falla sistémica
  - outage
  - caída de servicio
  - error operativo
  - incidente operacional
  - retraso de actividades productivas
  - suspensión de actividades
ambiental_social:
  - licencia ambiental
  - sanción ambiental
  - proceso sancionatorio ambiental
  - conflicto con comunidades
  - conflicto armado
  - protesta
  - bloqueo
  - manifestación
  - trabajo infantil
  - trabajo forzoso
  - contratación ilegal
  - área protegida
  - traslape
  - impacto ambiental
  - cambio climático
  - biodiversidad
  - contaminación
  - desplazamiento involuntario
  - accidente laboral
  - incidente laboral
  - fatalidad
  - suspensión de licencia ambiental
  - multa por incumplimiento
  - inundación
  - sequía
  - contaminación a río
  - derrame
  - incumplimiento compromisos ambientales
  - incendio
  - tala ilegal
  - compensación ecológica
  - concesión de agua
  - estudio de impacto ambiental
  - hallazgo arqueológico
  - comunidad indígena
  - denuncia ambiental
  - denuncia laboral
  - deforestación
  - sanción ASA
  - vertido sin permiso
  - sanción ministerio de trabajo
  - conflicto laboral
  - PAMA
  - programa de adecuación y manejo ambiental
